version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo "Building the application"
  post_build:
    commands:
      - echo "Build complete!"
artifacts:
  files:
    - '**/*'

