version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install flask
  build:
    commands:
      - echo "Starting the build process"
      - python app.py &
artifacts:
  files:
    - '**/*'

