version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Building the application"
  post_build:
    commands:
      - echo "Copying files to web server directory"
      - sudo cp -r * /var/www/html/
artifacts:
  files:
    - '**/*'
